SET GLOBAL local_infile = true;

LOAD DATA LOCAL INFILE '/Users/natal/Downloads/books_1.Best_Books_Ever.csv'
INTO TABLE Books
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES;

SELECT * FROM Books;

LOAD DATA LOCAL INFILE '/Users/natal/Downloads/BX-Users2.csv'
INTO TABLE BC_Users
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES;

SELECT * FROM BC_Users;

LOAD DATA LOCAL INFILE '/Users/natal/Downloads/BX-Book-Ratings2.csv'
INTO TABLE BC_User_Ratings
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES;

SELECT * FROM BC_User_Ratings;

DELETE FROM BC_User_Ratings WHERE ISBN NOT IN 
(SELECT ISBN from Books);

