CREATE DATABASE BookDB2;
USE BookDB2;

CREATE TABLE Books (
BookID INTEGER PRIMARY KEY,
Title TEXT,
Series_Name TEXT,
Author TEXT,
Rating_GR INTEGER,
Language TEXT,
ISBN TEXT,
BookFormat TEXT,
Pages INTEGER,
Publisher TEXT,
NumRatings_GR INTEGER,
RatingsByStars_GR TEXT,
LikedPercent INTEGER,
BBEScore INTEGER,
BBEVotes INTEGER,
Price TEXT);

CREATE TABLE Genres (
GenreID INTEGER PRIMARY KEY,
Name TEXT) ;

CREATE TABLE Book_Genres (
BookID INTEGER,
GenreID INTEGER,
PRIMARY KEY (BookID, GenreID),
FOREIGN KEY (BookID) REFERENCES Books (BookID),
FOREIGN KEY (GenreID) REFERENCES Genres (GenreID)) ;

CREATE TABLE Awards (
AwardID INTEGER PRIMARY KEY,
Name TEXT);

CREATE TABLE Book_Awards (
BookID INTEGER,
AwardID INTEGER,
PRIMARY KEY (BookID, AwardID),
FOREIGN KEY (BookID) REFERENCES Books (BookID),
FOREIGN KEY (AwardID) REFERENCES Awards (AwardID)) ;

CREATE TABLE BC_Users (
UserID INTEGER PRIMARY KEY,
City TEXT,
State TEXT,
Country TEXT,
Age INTEGER);

CREATE TABLE BC_User_Ratings (
UserID INTEGER,
BookID INTEGER,
RATING INTEGER,
PRIMARY KEY (UserID, BookID),
FOREIGN KEY (BookID) REFERENCES Books (BookID),
FOREIGN KEY (UserID) REFERENCES BC_Users (UserID));