CREATE DATABASE BookDB;
USE BookDB;

CREATE TABLE Books (
BookID TINYINT (8) PRIMARY KEY,
Title VARCHAR (319),
Series_Name VARCHAR (218),
Author VARCHAR (669),
Rating_GR TINYINT (1),
Language TEXT (80000),
ISBN VARCHAR (13),
BookFormat TINYTEXT,
Pages TINYINT (5),
Publisher VARCHAR (6000),
NumRatings_GR MEDIUMINT (7),
RatingsByStars_GR VARCHAR (760),
LikedPercent TINYINT (2),
BBEScore TINYINT (10),
BBEVotes TINYINT (5),
Price DECIMAL (2,2));

CREATE TABLE Genres (
GenreID TINYINT (4) PRIMARY KEY,
Name VARCHAR (31)) ;

CREATE TABLE Book_Genres (
BookID TINYINT (8),
GenreID TINYINT (4),
PRIMARY KEY (BookID, GenreID),
FOREIGN KEY (BookID) REFERENCES Books (BookID),
FOREIGN KEY (GenreID) REFERENCES Genres (GenreID)) ;

CREATE TABLE Awards (
AwardID TINYINT(4) PRIMARY KEY,
Name VARCHAR (185));

CREATE TABLE Book_Awards (
BookID TINYINT (8),
AwardID TINYINT(4),
PRIMARY KEY (BookID, AwardID),
FOREIGN KEY (BookID) REFERENCES Books (BookID),
FOREIGN KEY (AwardID) REFERENCES Awards (AwardID)) ;

CREATE TABLE BC_Users (
UserID TINYINT (6) PRIMARY KEY,
City VARCHAR (50),
State VARCHAR (81),
Country VARCHAR (40),
Age TINYINT (3));

CREATE TABLE BC_User_Ratings (
UserID TINYINT (6),
BookID TINYINT (8),
RATING TINYINT (2),
PRIMARY KEY (UserID, BookID),
FOREIGN KEY (BookID) REFERENCES Books (BookID),
FOREIGN KEY (UserID) REFERENCES BC_Users (UserID));